from app.schemas.auth import *
from app.schemas.academic import *
from app.schemas.communication import *
from app.schemas.complaint import *
from app.schemas.finance import *
from app.schemas.kitchen import *
from app.schemas.library import *
from app.schemas.performance import *
from app.schemas.rag import *
