"""Initial schema creation

Revision ID: 71e359b42c82
Revises: 
Create Date: 2026-08-13 15:08:38.961645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e359b42c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centers_code'), 'centers', ['code'], unique=True)
    op.create_index(op.f('ix_centers_id'), 'centers', ['id'], unique=False)
    op.create_table('public_inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('routed_to', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_inquiries_id'), 'public_inquiries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('center_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_center_id'), 'users', ['center_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('academic_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('ustad_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ustad_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ustad_id', 'student_id', name='uq_ustad_student_thread')
    )
    op.create_index(op.f('ix_academic_threads_id'), 'academic_threads', ['id'], unique=False)
    op.create_table('finance_categories',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fund_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'name', name='uq_center_category_name')
    )
    op.create_index(op.f('ix_finance_categories_center_id'), 'finance_categories', ['center_id'], unique=False)
    op.create_table('halqas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('ustad_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ustad_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halqas_id'), 'halqas', ['id'], unique=False)
    op.create_table('hifz_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('ustad_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('sabaq_details', sa.String(length=255), nullable=True),
    sa.Column('sabaq_grade', sa.String(length=50), nullable=True),
    sa.Column('sabqi_details', sa.String(length=255), nullable=True),
    sa.Column('sabqi_grade', sa.String(length=50), nullable=True),
    sa.Column('manzil_details', sa.String(length=255), nullable=True),
    sa.Column('manzil_grade', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ustad_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'log_date', name='uq_hifz_student_date')
    )
    op.create_index(op.f('ix_hifz_logs_id'), 'hifz_logs', ['id'], unique=False)
    op.create_table('internal_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_tickets_id'), 'internal_tickets', ['id'], unique=False)
    op.create_table('kitab_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('ustad_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('kitab_name', sa.String(length=255), nullable=False),
    sa.Column('chapter_or_topic', sa.String(length=255), nullable=True),
    sa.Column('mutalaa_completed', sa.Boolean(), nullable=True),
    sa.Column('comprehension_grade', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ustad_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitab_logs_id'), 'kitab_logs', ['id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('parent_student_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_student_relations_id'), 'parent_student_relations', ['id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_zakat_eligible', sa.Boolean(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('sponsor_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('super_admin_escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('complaint_details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('super_admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admin_escalations_id'), 'super_admin_escalations', ['id'], unique=False)
    op.create_table('tarbiyyah_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('is_on_leave', sa.Boolean(), nullable=True),
    sa.Column('fajr', sa.String(length=50), nullable=True),
    sa.Column('zuhr', sa.String(length=50), nullable=True),
    sa.Column('asr', sa.String(length=50), nullable=True),
    sa.Column('maghrib', sa.String(length=50), nullable=True),
    sa.Column('isha', sa.String(length=50), nullable=True),
    sa.Column('adab_score', sa.Integer(), nullable=True),
    sa.Column('behavior_remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('adab_score >= 1 AND adab_score <= 5', name='chk_adab_score_range'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'log_date', name='uq_tarbiyyah_student_date')
    )
    op.create_index(op.f('ix_tarbiyyah_logs_id'), 'tarbiyyah_logs', ['id'], unique=False)
    op.create_table('academic_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['academic_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_messages_id'), 'academic_messages', ['id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('sent_by', sa.String(length=36), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('target_halqa_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_halqa_id'], ['halqas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_table('halqa_enrollments',
    sa.Column('halqa_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['halqa_id'], ['halqas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('halqa_id', 'student_id')
    )
    op.create_table('transactions',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_for_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_for_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_center_id'), 'transactions', ['center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_center_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('halqa_enrollments')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_academic_messages_id'), table_name='academic_messages')
    op.drop_table('academic_messages')
    op.drop_index(op.f('ix_tarbiyyah_logs_id'), table_name='tarbiyyah_logs')
    op.drop_table('tarbiyyah_logs')
    op.drop_index(op.f('ix_super_admin_escalations_id'), table_name='super_admin_escalations')
    op.drop_table('super_admin_escalations')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_parent_student_relations_id'), table_name='parent_student_relations')
    op.drop_table('parent_student_relations')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_kitab_logs_id'), table_name='kitab_logs')
    op.drop_table('kitab_logs')
    op.drop_index(op.f('ix_internal_tickets_id'), table_name='internal_tickets')
    op.drop_table('internal_tickets')
    op.drop_index(op.f('ix_hifz_logs_id'), table_name='hifz_logs')
    op.drop_table('hifz_logs')
    op.drop_index(op.f('ix_halqas_id'), table_name='halqas')
    op.drop_table('halqas')
    op.drop_index(op.f('ix_finance_categories_center_id'), table_name='finance_categories')
    op.drop_table('finance_categories')
    op.drop_index(op.f('ix_academic_threads_id'), table_name='academic_threads')
    op.drop_table('academic_threads')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_center_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_public_inquiries_id'), table_name='public_inquiries')
    op.drop_table('public_inquiries')
    op.drop_index(op.f('ix_centers_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_code'), table_name='centers')
    op.drop_table('centers')
    # ### end Alembic commands ###
