"""Initial auth and tenant tables

Revision ID: 1ef6ae7b79aa
Revises: 
Create Date: 2026-08-13 14:00:09.637428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1ef6ae7b79aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_remark_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_remark_vectors_id'))

    op.drop_table('student_remark_vectors')
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_id'))

    op.drop_table('document_embeddings')
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_finance_categories_id'))
        batch_op.create_index(batch_op.f('ix_finance_categories_center_id'), ['center_id'], unique=False)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.create_index(batch_op.f('ix_transactions_center_id'), ['center_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_index(batch_op.f('ix_users_center_id'), ['center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_center_id'))
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_center_id'))
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_categories_center_id'))
        batch_op.create_index(batch_op.f('ix_finance_categories_id'), ['id'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('document_embeddings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('center_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('document_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chunk_text', sa.TEXT(), nullable=False),
    sa.Column('embedding_json', sqlite.JSON(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_id'), ['id'], unique=False)

    op.create_table('student_remark_vectors',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('center_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('ustad_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('chunk_text', sa.TEXT(), nullable=False),
    sa.Column('embedding_json', sqlite.JSON(), nullable=True),
    sa.Column('week_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('month_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('year_val', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ustad_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_remark_vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_remark_vectors_id'), ['id'], unique=False)

    # ### end Alembic commands ###
